# Exploring & Testing Use of NURBS in DIC
## Sam Potter
## Current: 12/7/18

## Path and Imports

In [3]:
# bootstrap $PATH
import sys
import os
sys.path.extend(['C:\\Users\\potterst1\\Desktop\Repositories\BitBucket\dic',
                 'C:/Users/potterst1/Desktop/Repositories/BitBucket/dic'])
sys.path.extend(['/workspace/stpotter/git/bitbucket/dic'])
import warnings
from dic import nurbs
from dic import fileIO
from dic import numerics
from dic import analysis
from dic import image_processing
import cv2
from matplotlib import pyplot as plt
import numpy as np
import scipy.optimize as sciopt
from geomdl import BSpline as bs
from geomdl import utilities as gutil

## Magics

In [2]:
%matplotlib inline

## Setup surface

In [10]:
x = np.linspace(0, 1, 4)
y = np.linspace(0, 1, 4)
coords = np.zeros((len(x) * len(x), 2))
k = 0
for i in range(0, len(x)):
    for j in range(0, len(y)):
        coords[k, :] = np.array([x[i], y[j]])
        k += 1

In [12]:
coords

array([[0.        , 0.        ],
       [0.        , 0.33333333],
       [0.        , 0.66666667],
       [0.        , 1.        ],
       [0.33333333, 0.        ],
       [0.33333333, 0.33333333],
       [0.33333333, 0.66666667],
       [0.33333333, 1.        ],
       [0.66666667, 0.        ],
       [0.66666667, 0.33333333],
       [0.66666667, 0.66666667],
       [0.66666667, 1.        ],
       [1.        , 0.        ],
       [1.        , 0.33333333],
       [1.        , 0.66666667],
       [1.        , 1.        ]])

In [19]:
surf = bs.Surface()
surf.degree_u = 3
surf.degree_v = 3

num_ctrlpts = np.sqrt(len(coords)).astype('int')

surf.set_ctrlpts(coords.tolist(), num_ctrlpts, num_ctrlpts)

surf.knotvector_u = gutil.generate_knot_vector(surf.degree_u, num_ctrlpts)
surf.knotvector_v = gutil.generate_knot_vector(surf.degree_v, num_ctrlpts)

surf.delta = 0.001

In [24]:
pts = np.array(surf.evalpts)

In [25]:
len(pts)

1002001

In [26]:
pts[0, :]

array([0., 0.])

In [27]:
pts[1, :]

array([0.   , 0.001])

In [28]:
surf.surfpt(0, 0.001)

[0.0, 0.001]

In [29]:
pts[20, :]

array([0.  , 0.02])

In [30]:
surf.surfpt(0, 20 * 0.001)

[0.0, 0.019999999999999997]

In [31]:
np.sqrt(len(pts))

1001.0

In [33]:
surf.surfpt(0.001, 20 * 0.001)

[0.0009999999999999998, 0.02]

In [38]:
pts[1020, :]

array([0.001, 0.019])

In [36]:
len(np.arange(0, 1, 0.001))

1000

In [39]:
surf.delta

(0.001, 0.001)

In [40]:
surf.delta_u

0.001

In [41]:
surf.delta[0]

0.001

In [43]:
1020.0 % 1000.0

20.0

In [44]:
1020 // 1000

1

In [45]:
10000 // 1000

10

In [46]:
val = 0.5
A = np.random.random((4, 4))
A

array([[0.03911235, 0.00652965, 0.60523545, 0.85980101],
       [0.78802295, 0.00521731, 0.9547595 , 0.88455318],
       [0.75735154, 0.49790571, 0.68796608, 0.41659996],
       [0.36533644, 0.3769866 , 0.15433662, 0.93712192]])

In [49]:
X = np.abs(A-val)
X

array([[0.46088765, 0.49347035, 0.10523545, 0.35980101],
       [0.28802295, 0.49478269, 0.4547595 , 0.38455318],
       [0.25735154, 0.00209429, 0.18796608, 0.08340004],
       [0.13466356, 0.1230134 , 0.34566338, 0.43712192]])

In [53]:
point = [0.5, 0.5]
diff = np.sqrt(np.square(pts[:, 0] - point[0]) + np.square(pts[:, 1] - point[1]))

In [54]:
diff.shize

AttributeError: 'numpy.ndarray' object has no attribute 'shize'

In [55]:
diff.size

1002001

In [56]:
diff.min()

0.0

In [57]:
idx = np.where(diff == diff.min())

In [58]:
idx

(array([501000]),)

In [60]:
pts[idx[0], :]

array([[0.5, 0.5]])

In [76]:
foo = np.zeros((2,) + X.shape)

In [77]:
foo.shape

(2, 4, 4)

In [78]:
foo

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])