# Exploring & Testing Use of NURBS in DIC
## Sam Potter
## Current: 12/7/18

## Path and Imports

In [1]:
# bootstrap $PATH
import sys
import os
sys.path.extend(['C:\\Users\\potterst1\\Desktop\Repositories\BitBucket\dic',
                 'C:/Users/potterst1/Desktop/Repositories/BitBucket/dic'])
sys.path.extend(['/workspace/stpotter/git/bitbucket/dic'])
import warnings
from dic import nurbs
from dic import fileIO
from dic import numerics
from dic import analysis
from dic import image_processing
import cv2
from matplotlib import pyplot as plt
import numpy as np
import scipy.optimize as sciopt
from geomdl import BSpline as bs
from geomdl import utilities as gutil

## Magics

In [2]:
%matplotlib inline

## Setup surface

In [3]:
x = np.linspace(0, 1, 4)
y = np.linspace(0, 1, 4)
coords = np.zeros((len(x) * len(x), 2))
k = 0
for i in range(0, len(x)):
    for j in range(0, len(y)):
        coords[k, :] = np.array([x[i], y[j]])
        k += 1

In [4]:
coords

array([[0.        , 0.        ],
       [0.        , 0.33333333],
       [0.        , 0.66666667],
       [0.        , 1.        ],
       [0.33333333, 0.        ],
       [0.33333333, 0.33333333],
       [0.33333333, 0.66666667],
       [0.33333333, 1.        ],
       [0.66666667, 0.        ],
       [0.66666667, 0.33333333],
       [0.66666667, 0.66666667],
       [0.66666667, 1.        ],
       [1.        , 0.        ],
       [1.        , 0.33333333],
       [1.        , 0.66666667],
       [1.        , 1.        ]])

In [5]:
surf = bs.Surface()
surf.degree_u = 3
surf.degree_v = 3

num_ctrlpts = np.sqrt(len(coords)).astype('int')

surf.set_ctrlpts(coords.tolist(), num_ctrlpts, num_ctrlpts)

surf.knotvector_u = gutil.generate_knot_vector(surf.degree_u, num_ctrlpts)
surf.knotvector_v = gutil.generate_knot_vector(surf.degree_v, num_ctrlpts)

surf.delta = 0.001

In [6]:
pts = np.array(surf.evalpts)

In [7]:
len(pts)

1002001

In [8]:
pts[0, :]

array([0., 0.])

In [9]:
pts[1, :]

array([0.   , 0.001])

In [10]:
surf.surfpt(0, 0.001)

[0.0, 0.001]

In [11]:
pts[20, :]

array([0.  , 0.02])

In [12]:
surf.surfpt(0, 20 * 0.001)

[0.0, 0.019999999999999997]

In [13]:
np.sqrt(len(pts))

1001.0

In [14]:
surf.surfpt(0.001, 20 * 0.001)

[0.0009999999999999998, 0.02]

In [15]:
pts[1020, :]

array([0.001, 0.019])

In [16]:
len(np.arange(0, 1, 0.001))

1000

In [17]:
surf.delta

(0.001, 0.001)

In [18]:
surf.delta_u

0.001

In [19]:
surf.delta[0]

0.001

In [20]:
1020.0 % 1000.0

20.0

In [21]:
1020 // 1000

1

In [22]:
10000 // 1000

10

In [23]:
val = 0.5
A = np.random.random((4, 4))
A

array([[0.91713862, 0.47291656, 0.33228849, 0.30136377],
       [0.27534311, 0.4196313 , 0.16537578, 0.5887817 ],
       [0.79530857, 0.53284335, 0.49863877, 0.59188912],
       [0.0104885 , 0.49009923, 0.38502554, 0.15586965]])

In [24]:
X = np.abs(A-val)
X

array([[0.41713862, 0.02708344, 0.16771151, 0.19863623],
       [0.22465689, 0.0803687 , 0.33462422, 0.0887817 ],
       [0.29530857, 0.03284335, 0.00136123, 0.09188912],
       [0.4895115 , 0.00990077, 0.11497446, 0.34413035]])

In [25]:
point = [0.5, 0.5]
diff = np.sqrt(np.square(pts[:, 0] - point[0]) + np.square(pts[:, 1] - point[1]))

In [26]:
diff.shize

AttributeError: 'numpy.ndarray' object has no attribute 'shize'

In [27]:
diff.size

1002001

In [28]:
diff.min()

0.0

In [29]:
idx = np.where(diff == diff.min())

In [30]:
idx

(array([501000]),)

In [31]:
pts[idx[0], :]

array([[0.5, 0.5]])

In [32]:
foo = np.zeros((2,) + X.shape)

In [33]:
foo.shape

(2, 4, 4)

In [34]:
foo

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [42]:
surf.surfpt(0.0, 0.6)

[0.0, 0.5999999999999999]